#!/usr/bin/env bash
# Construye un tarball reproducible listo para subir a Zenodo.
# - Verifica que los tests pasan.
# - Genera el bundle con manifest, checksums y versión taggeada.
set -euo pipefail

cd "$(dirname "$0")/.."
PROJECT_DIR="$PWD"

# Versión desde pyproject.toml
VERSION=$(grep -m1 '^version = ' pyproject.toml | sed -E 's/version = "([^"]+)"/\1/')
DATE=$(date +%Y-%m-%d)
RELEASE_NAME="scholarly-profile-auditor-v${VERSION}"
DIST_DIR="dist"

echo "============================================================"
echo "Building Zenodo release: ${RELEASE_NAME}"
echo "============================================================"

# 1. Tests verde
echo ""
echo "→ 1/5 Ejecutando tests..."
if [ ! -d ".venv" ]; then
  python3.11 -m venv .venv 2>/dev/null || python3 -m venv .venv
fi
source .venv/bin/activate
pip install --quiet -e ".[dev]" 2>&1 | tail -2
PYTHONPATH=. python -m pytest -q --no-header 2>&1 | tail -5
echo ""

# 2. Limpiar caches
echo "→ 2/5 Limpiando caches..."
find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
find . -type d -name ".pytest_cache" -exec rm -rf {} + 2>/dev/null || true
find . -type d -name "*.egg-info" -exec rm -rf {} + 2>/dev/null || true
rm -rf .ruff_cache .mypy_cache build 2>/dev/null || true

# 3. Crear manifest
echo "→ 3/5 Generando MANIFEST.txt..."
mkdir -p "$DIST_DIR"
{
  echo "# Scholarly Profile Auditor — Zenodo release manifest"
  echo "# Version: $VERSION"
  echo "# Date: $DATE"
  echo "# Generated by build_zenodo_release.sh"
  echo ""
  echo "## Files (path, size_bytes, sha256)"
  find . \
    -type f \
    -not -path './.git/*' -not -path './.venv/*' -not -path './dist/*' \
    -not -path './out/*' -not -path './node_modules/*' \
    -not -name '*.pyc' -not -name '.DS_Store' \
    | sort | while read -r f; do
      size=$(wc -c <"$f" | tr -d ' ')
      sha=$(sha256sum "$f" | awk '{print $1}')
      printf '%s  %10d  %s\n' "$sha" "$size" "${f#./}"
    done
} > "$DIST_DIR/MANIFEST.txt"

# 4. Crear tarball
echo "→ 4/5 Empaquetando tarball..."
TARBALL="$DIST_DIR/${RELEASE_NAME}.tar.gz"
tar -czf "$TARBALL" \
    --exclude='.git' --exclude='.venv' --exclude='dist' \
    --exclude='out' --exclude='node_modules' \
    --exclude='__pycache__' --exclude='*.pyc' \
    --exclude='.pytest_cache' --exclude='.mypy_cache' --exclude='.ruff_cache' \
    --exclude='.DS_Store' \
    --transform "s,^\./,${RELEASE_NAME}/," \
    .

# 5. Checksum del tarball
SHA=$(sha256sum "$TARBALL" | awk '{print $1}')
SIZE=$(wc -c <"$TARBALL")
echo "$SHA  $TARBALL" > "$DIST_DIR/${RELEASE_NAME}.sha256"

echo ""
echo "============================================================"
echo " Release listo:"
echo "   Tarball: $TARBALL  (${SIZE} bytes)"
echo "   SHA-256: $SHA"
echo "   Manifest: $DIST_DIR/MANIFEST.txt"
echo "============================================================"
echo ""
echo "Próximos pasos:"
echo "  1. Crea un release en GitHub con tag v${VERSION}."
echo "  2. Si tu repo está conectado a Zenodo, el release se archiva"
echo "     automáticamente con un DOI."
echo "  3. Sustituye 'PLACEHOLDER' en CITATION.cff y .zenodo.json"
echo "     con el DOI real que Zenodo te asigne."
